.TH std::bad_function_call 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   Defined in header <functional>
   class bad_function_call;        \fI(since C++11)\fP

   std::bad_function_call is the type of the exception thrown by
   std::function::operator() if the function wrapper has no target.

   std-bad function call-inheritance.svg
   About this image

                                   Inheritance diagram

.SH Contents

     * 1 Member functions
     * 2
       std::bad_function_call::bad_function_call()

          * 2.1 Parameters
          * 2.2 Exceptions
          * 2.3 Inherited from
            std::exception

               * 2.3.1 Member functions
               * 2.3.2 Example
               * 2.3.3 See also

.SH Member functions

   constructor   bad_function_call()
                 \fI(public member function)\fP

                       std::bad_function_call::bad_function_call()

   bad_function_call();

   Constructs a new instance of std::bad_function_call.

.SH Parameters

   \fI(none)\fP

.SH Exceptions

   noexcept specification:
   noexcept

Inherited from std::exception

.SH Member functions

   destructor   destructs the exception object
   \fB[virtual]\fP    \fI(virtual public member function of std::exception)\fP
   what         returns an explanatory string
   \fB[virtual]\fP    \fI(virtual public member function of std::exception)\fP

.SH Example

   
// Run this code

 #include <iostream>
 #include <functional>

 int main()
 {
     std::function<int()> f = nullptr;
     try {
         f();
     } catch(const std::bad_function_call& e) {
         std::cout << e.what() << '\\n';
     }
 }

.SH Output:

 bad function call

.SH See also

   function wraps callable object of any type with specified function call signature
   \fI(C++11)\fP  \fI(class template)\fP
